### ISSUE TITLE
Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found)

### ISSUE THREAD

**Issue by jakob-p** [mio42-GmbH/Validierungspaket-MIO-DiGA-Toolkit#4]
We get this error when trying to running the validator:

**Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found)**

full error log:

```
java -jar validator_cli.jar bundle.xml -ig "hl7.fhir.core#4.0.1" -ig KBV-Base -ig HL7-Base-de -ig FHIR-Specification\ -recurse

FHIR Validation tool Version 5.6.84 (Git# b0d3dae1491b). Built 2022-12-01T05:52:28.96Z (196 days old)
  Java:   11.0.17 from /Users/macbook/.sdkman/candidates/java/11.0.17-tem on aarch64 (64bit). 6144MB available
  Paths:  Current = /Users/macbook/Documents/MIO/Validierungspaket-MIO-DiGA-Toolkit-v1.1.0-r1, Package Cache = /Users/macbook/.fhir/packages
  Params: export.xml -ig hl7.fhir.core#4.0.1 -ig KBV-Base -ig HL7-Base-de -ig "FHIR-Specification -recurse"
  Jurisdiction: Germany
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1.: - 4576 resources (00:02.748)
  Load hl7.terminology#5.1.0 - 4180 resources (00:00.852)
  Load R5 ExtensionsException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to fetch: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:540)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromCIBuild(FilesystemPackageCacheManager.java:560)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:520)
	at org.hl7.fhir.r5.conformance.R5ExtensionsLoader.load(R5ExtensionsLoader.java:81)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:378)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:356)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:283)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
Caused by: java.io.IOException: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.SimpleHTTPClient$HTTPResult.checkThrowException(SimpleHTTPClient.java:75)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:534)
	... 7 more

```

**Comment by dkipping-mio42** [comment]
Hi @jakob-p ,

Two quick things to check:
- are you behind any proxy/VPN? (e.g. of your company network)
- if yes: try disabling it or running the command on a local machine outside the proxy network
- if not: could you try to use the most current validator_cli.jar, instead of the one we provided: 
  https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/6.0.15
  
Could you try the exact same command just replacing the validator and report back whether you still receive the error on your system?  

Best
Dennis

**Comment by jakob-p** [comment]
Hi @dkipping-mio42 ,

thank you for your help, using the latest version of the validator-cli.jar solved the issue for us 👍
