### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by karolkorzen** [mio42-GmbH/Validierungspaket-MIO-DiGA-Toolkit#5]
I have an issue with running validation of example datasets.
I've tried both latest and 5.6.84 (mentioned in README) version. 
Is there any solution for it? Shall I use other validator version?

5.6.84
```
❯ sudo java -jar validator_cli.jar .\Example\REAL_EXAMPLE_2_KBV_PR_MIO_DIGA_Bundle.xml -ig "hl7.fhir.core#4.0.1" -ig .\KBV-Base -ig .\HL7-Base-de -ig .\FHIR-Specification -recurse
FHIR Validation tool Version 5.6.84 (Git# b0d3dae1491b). Built 2022-12-01T05:52:28.96Z (236 days old)
  Java:   20.0.1 from /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home on aarch64 (64bit). 4096MB available
  Paths:  Current = /Users/user/Downloads/Validierungspaket-MIO-DiGA-Toolkit-master, Package Cache = /var/root/.fhir/packages
  Params: .ExampleREAL_EXAMPLE_2_KBV_PR_MIO_DIGA_Bundle.xml -ig hl7.fhir.core#4.0.1 -ig .KBV-Base -ig .HL7-Base-de -ig .FHIR-Specification -recurse
  Jurisdiction: Poland
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1Installing hl7.fhir.r4.core#4.0.1 to the package cache
  Fetching:
....................................................................................................
  Installing: .................................................................................................... done.
.:Installing hl7.fhir.xver-extensions#0.0.11 to the package cache
  Fetching:

  Installing:  done.
 - 4576 resources (00:07.582)
Installing hl7.terminology#5.2.0 to the package cache
  Fetching:
....................................................................................
  Installing: .................................................................................... done.
Installing hl7.fhir.uv.extensions.r4#1.0.0 to the package cache
  Fetching:
....................................
  Installing: .................................... done.
  Load hl7.fhir.uv.extensions.r4#1.0.0 - 1328 resources (00:08.942)
  Load hl7.terminology#5.2.0 - 4195 resources (00:00.841)
  Load R5 ExtensionsException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to fetch: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:540)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromCIBuild(FilesystemPackageCacheManager.java:560)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:520)
	at org.hl7.fhir.r5.conformance.R5ExtensionsLoader.load(R5ExtensionsLoader.java:81)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:378)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:356)
	at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:283)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
Caused by: java.io.IOException: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
	at org.hl7.fhir.utilities.SimpleHTTPClient$HTTPResult.checkThrowException(SimpleHTTPClient.java:75)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:534)
	... 7 more
```

latest version 6.0.22

```
❯ sudo java -jar validator_cli.jar .\Example\REAL_EXAMPLE_3_KBV_PR_MIO_DIGA_Bundle.xml -ig "hl7.fhir.core#4.0.1" -ig .\KBV-Base -ig .\HL7-Base-de -ig .\FHIR-Specification -recurse
Password:
FHIR Validation tool Version 6.0.22 (Git# b7fd3be91031). Built 2023-07-22T17:06:38.54Z (63 hours old)
  Java:   20.0.1 from /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home on aarch64 (64bit). 4096MB available
  Paths:  Current = /Users/user/Downloads/Validierungspaket-MIO-DiGA-Toolkit-master, Package Cache = /var/root/.fhir/packages
  Params: .ExampleREAL_EXAMPLE_3_KBV_PR_MIO_DIGA_Bundle.xml -ig hl7.fhir.core#4.0.1 -ig .KBV-Base -ig .HL7-Base-de -ig .FHIR-Specification -recurse
  Locale: Poland/PL
  Jurisdiction: Poland
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4576 resources (00:04.250)
  Load hl7.fhir.uv.extensions.r4#1.0.0 - 1328 resources (00:00.462)
  Load hl7.terminology#5.2.0 - 4195 resources (00:01.315)
  Load hl7.terminology.r5#5.0.0 - 4174 resources (00:00.810)
  Load hl7.fhir.uv.extensions#1.0.0 - 1328 resources (00:00.014)
  Terminology server http://tx.fhir.org - Version 2.1.0 (00:01.372)
  Load .KBV-BaseException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to find/resolve/read -ig .KBV-Base
	at org.hl7.fhir.validation.IgLoader.loadIgSource(IgLoader.java:290)
	at org.hl7.fhir.validation.IgLoader.loadIg(IgLoader.java:127)
	at org.hl7.fhir.validation.cli.services.ValidationService.loadIgsAndExtensions(ValidationService.java:509)
	at org.hl7.fhir.validation.cli.services.ValidationService.buildValidationEngine(ValidationService.java:454)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:435)
	at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:425)
	at org.hl7.fhir.validation.ValidatorCli.getValidationEngine(ValidatorCli.java:342)
	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:307)
	at org.hl7.fhir.validation.ValidatorCli.readParamsAndExecuteTask(ValidatorCli.java:171)
	at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:204)
```

**Comment by dkipping-mio42** [comment]
Hi,

I can confirm, that our used version of the validator causes error messages for the R5 extension downloads and subsequently for the generation of the snapshots.
Seems like HL7 changed the server API in between and older validator version might not be able to communicate properly with it anymore.
This causes a short delay, however the validation does continue to run through afterwards for me.
Since it might cause instability of the validator, I would still recommend to go with a more recent version.

I tested with the newer version 6.0.22 named by you.
This still yields problems for converting the Body_Temperature to R5 internally, but apart from that no further errors seem to arise.
The validation results are the same.

I guess your error with the newer validator ist only caused by the fact that you are on a UNIX system (mac os / linux) and are using the Windows paths.
When on mac os / linux, you have to replace the back-slashes with forward-facing-slashes: "\" --> "/"

Hope this helps

**Comment by karolkorzen** [comment]
Thank you! Indeed it was a windows command
